<?php html_page_top('Kanban Board'); ?>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="<?php echo plugin_file('kanban.css') ?>"/>

<form>
    <input type="hidden" name="page" value="KanbanBoard/kanban" />
    <label>Severity
        <select name="severity">
            <option></option>
            <?php print_enum_string_option_list('severity', $this->severity); ?>
        </select>
    </label>
    <label>Versions
        <select name="versions">
            <option></option>
            <?php
                foreach ($this->versions as $version) {
                    $output = '<option value="' . $version[0] . '"';
                    if ($version[1] == "true") {
                        $output .= ' selected="selected" ';
                    }
                    $output .= '>' . $version[0] . '</option>';
                    echo $output;
                }
            ?>
        </select>
    </label>
    <input type="submit" value="Filter" />
</form>

<div class="kanbanboard ui-helper-clearfix" id="reloadTarget">
<?= $this->renderLists(); ?>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
<script src="plugins/KanbanBoard/pages/kanban.js"></script>
<?php html_page_bottom(); ?>
